// Episode 6 (Julius Caesar, Rome 44 BC) — caption cue data for qc_pass.mjs.
//
// FORMAT CHANGE (owner-locked 2026-08-23, channel default per CLAUDE.md
// "Caption system"): word-synced CHUNK captions, migrated from this
// episode's own previous full-line cues (preserved at
// captions_data_lines_backup.mjs, which remains the line-window ground
// truth this chunk pipeline validates its whisper timing against):
//   - 1-2 word chunks, each REPLACING the previous (no accumulation)
//   - a chunk is on screen only while its words are spoken
//   - silence/pauses >= 0.35s = NO caption on screen
//   - hard cut in/out, no animation, ALL CAPS, serif (see SUB_STYLE)
//   - no speaker tags (channel-locked style)
//
// TIMING SOURCE: measured per-word timestamps from faster-whisper
// (small.en, int8, script-biased initial_prompt) run on each clip's own
// current (post-trim) rendered audio; script text is ground truth (whisper
// text only carries timing — words are fuzzy-matched back to the script so
// a mis-recognition can never change what's displayed). Generated by
// pai-pro-tooling/troy's make_word_chunks.py, copied into this project and
// adapted (asset filenames have no `_v1` suffix here; added a guard for
// clip9's empty-captions case, which the troy reference never hit and
// which crashed on a division by zero — troy's episode had no dialogue-free
// clips). Match rate was 92-100% on every clip except clip7 (see below);
// benign mismatches (whisper mishearing "3/10" as "3 for 10", "Stay." as
// "STAY.", clip11b's already-documented "setting" mishearing) don't affect
// the displayed text, since script text is what's always shown — only
// timing precision is at stake, and those stayed within the same ~0.3-0.5s
// noise band established earlier this session.
//
// clip7 correction: shouted, multi-speaker delivery defeated whisper
// entirely — small.en produced a broken chunk merging "FIRST—" with "THE"
// across a real 0.94s pause (matching neither script nor audio), and
// bumping to medium.en made it WORSE (47% match, hallucinated a repeated
// phrase, still missed the shouted lines). Neither model size fixed it, so
// this is a genuine audio-character problem, not a model-capacity one.
// Fell back to the same "biggest real pauses are the true breaks, split
// what's left proportionally" methodology this project has used all along
// for windows with no finer-grained real measurement — applied here at
// chunk instead of line granularity, within this session's own
// silencedetect-verified line windows (0-2.5, 2.5-6.359, 7.303-13.072834,
// themselves independently re-verified multiple times this session,
// most recently in the full-episode transcript-first sweep). See
// fix_clip7_chunks.py for the exact method (processes each line's words
// independently so a shared interpolation pass can't bleed across a real
// line boundary — the bug that broke both whisper attempts).
//
// FOLLOW-UP FIX (owner flagged the proportional split still felt off):
// dense frame sampling (every ~0.1-0.3s across the disputed 2.5-6.359s
// window) showed sustained wide-open shouting through ~4.8-4.9s ("THE RED
// ONE! RED MEANS"), then a visibly shorter, quieter, already-turning-away
// articulation for "FIRST—" before the mouth is essentially inactive by
// ~5.3-5.4s — proportional-by-character-length had given "FIRST—" a full
// 0.965s (5.394-6.359), the same order as its neighbors, when the
// em-dash itself signals a cut-off/interrupted delivery, not a held one.
// Shortened "FIRST—" to 5.394-5.6. The real silencedetect boundary at
// 6.359 doesn't move (that's genuinely where audio energy — not
// necessarily HER speech; likely crowd/reverb tail as she turns — drops
// below threshold), but per the caption system's own rule a chunk is on
// screen only while its words are spoken, not for the full span of any
// non-silent audio, so the caption doesn't need to hold to 6.359 just
// because the room isn't fully quiet yet. This is this project's
// established mouth-frame-cross-check method (used earlier this session
// on clip 1's final line and clip 6's opening shout+push, and by Troy's
// own clip 10) applied retroactively to correct a chunk-pipeline fallback
// that turned out to still be wrong on first pass — proportional
// estimation within a verified window is better than nothing, but it is
// still an estimate, and this is a second, closer look at exactly the
// place that estimate was weakest.
//
// SECOND FOLLOW-UP FIX ("The sheriff..." line, owner flagged again):
// this line's internal word timing had never actually been measured —
// only estimated by splitting the 7.303-13.072834 window proportionally
// by word length, same limitation as "FIRST—" above but never revisited
// for this line specifically. Root cause turned out to be deeper than a
// bad proportional split: isolated the line's own audio (7.303-13.072834
// extracted as a standalone clip) and ran whisper on it fresh, away from
// the earlier shouting that had thrown off the full-clip transcription —
// it transcribed cleanly, but placed the words starting ~2.9s into the
// isolated clip (~10.2s absolute), nowhere near my 7.303 boundary at all.
// Frame-checked to confirm: she's not even facing the camera from
// 7.3-8.3s (watching Caesar's litter pass), only turns back and visibly
// starts speaking around 8.7-9.0s — meaning the real 7.303 silencedetect
// boundary was never her speech at all, just a stray reverb/energy tail
// from the earlier shout crossing back above threshold. The isolated
// whisper's own absolute offset still ran a little late against the
// visual (mouth clearly active by ~9.0-9.1s, not 10.2s), so the fix
// anchors the line's start to the frame-verified ~8.9s and carries
// forward whisper's own measured inter-word spacing from there (a real
// ASR measurement's relative timing is more trustworthy than another
// proportional-by-length guess, even when its absolute offset needed a
// visual correction). Net effect: the whole line shifted ~1.6s later
// than previously captioned, now 8.9-11.54, with the clip's last ~1.5s
// held on a trailing pause after "hat." rather than captioned — a
// natural post-punchline beat before the hard cut, not a gap needing to
// be filled. This is now the second time this exact line's caption
// needed a real fix rather than trusting a single proportional pass —
// worth remembering that "verified window, proportional split inside
// it" is a weaker guarantee than it sounds when the window's own
// boundary was itself derived from an estimate.
//
// THIRD FOLLOW-UP FIX ("The sheriff..." line, owner flagged a third time —
// "nothing wrong with her mouth, she's not even speaking it, there's a
// voice coming from the background"): the SECOND fix above was itself
// wrong, and the owner's new framing is exactly why. That fix anchored
// the line's start to "mouth clearly active by ~9.0-9.1s" — but a dense
// frame-by-frame re-check across the whole 9.2-11.7s span shows her
// mouth moving almost continuously throughout, with no discernible
// on/off transition anywhere in it. That continuous motion is a generic
// reacting-to-the-procession animation, not phoneme-accurate lip sync to
// this specific line, so "mouth looks active" was never capable of
// telling 8.9s apart from any other candidate start — it was the wrong
// signal to anchor on, full stop.
// Went back to pure audio, twice, deliberately avoiding the mistakes in
// both earlier passes:
//   - Ran completely UNBIASED whisper (no script initial_prompt) on two
//     independently-cut isolations — one starting at 10.3s, one starting
//     at 8.0s (chosen specifically so the earlier cut couldn't just be
//     echoing its own start-of-window back as "the first word," the
//     failure mode that produced the original 7.303 false anchor).
//     Both independently transcribed the line correctly AND placed its
//     start at 10.2-10.3s absolute — not 8.9s, not 7.303s.
//   - Ran Gemini eyes on AUDIO ONLY (video stripped out entirely, so it
//     had no mouth motion to lean on) — independently reported a clear,
//     close, single-voice line starting at 10.1s. A video-included pass
//     asked the same question had confidently claimed 9.9s with the full
//     9-word line compressed into 1.4s (not humanly plausible at a normal
//     delivery pace) and asserted the mouth "matches precisely" — almost
//     certainly the model pattern-matching her visible mouth motion onto
//     the audio rather than actually measuring it, the same trap the
//     8.9s frame-check fell into. That pass was discarded once the
//     audio-only pass (with the confound removed) disagreed with it.
//   - The 8.9-10.2s span itself: spectrogram shows genuinely unstructured,
//     diffuse energy there (no formant striations, unlike the clear
//     harmonic bursts from 10.2s on) — real crowd/reverb murmur, not
//     speech. That is almost certainly the literal "voice coming from
//     the background" the owner heard under the old 8.9s caption: audible
//     background noise sitting where a clear foreground line should have
//     been.
// Three independent methods (2x unbiased whisper, 1x audio-only Gemini),
// none sharing the other's failure mode, converged inside 0.2s of each
// other on ~10.2s. Final chunks anchor to 10.2s and carry forward
// whisper's measured inter-word spacing: 10.2-10.88 / 10.88-11.92 /
// 11.92-12.22 / 12.22-12.6 / 12.6-12.84 — leaving a ~0.23s trailing pause
// before the clip's hard cut at 13.072834, not the ~1.5s the second fix
// left (a real tell, in hindsight, that the second fix's line was
// anchored too early). Worth naming plainly: this line has now needed
// three fixes because the first two each trusted a signal that turned
// out not to be measuring what it was assumed to measure (a silencedetect
// boundary that was a reverb tail, then a mouth-motion cue that was
// generic animation, not lip sync). The thing that finally held up was
// two DIFFERENT audio measurements, cut two different ways, agreeing
// with each other — not any single clever check, however convincing it
// looked in isolation.
//
// Clip 6's chunk timing is a good independent cross-check of this
// session's own hard-won manual fix: Artemidorus's three-beat echo
// ("Red." / "Read first." / "A fine system.", found and fixed earlier
// this session — the previous data had merged the first two into one
// impossibly-short caption and left the third entirely uncaptioned) came
// back from real per-word measurement at 9.22-9.60 / 10.28-10.74 /
// 11.36-11.90 — closely matching the manually-derived 9.409-9.668 /
// 10.314-10.887 / 11.408-12.050998 from before. Independent confirmation
// the earlier fix was right, not just plausible.
//
// Clip 9 has no dialogue (its remaining ~1.7s of speech was trimmed out of
// the episode entirely per owner request) — 0 chunks, correctly empty.

export const CLIPS = [
  {
    id: "clip1",
    duration: 11.051995,
    captions: [
      { start: 0, end: 0.34, text: "ROME." },
      { start: 0.68, end: 1.34, text: "MARCH 15TH," },
      { start: 1.34, end: 1.96, text: "44 BC." },
      { start: 2.54, end: 3.1, text: "THE IDES." },
      { start: 3.52, end: 4.06, text: "SIXTY SENATORS" },
      { start: 4.06, end: 4.5, text: "ARE WALKING" },
      { start: 4.5, end: 4.82, text: "THROUGH THIS" },
      { start: 4.82, end: 5.16, text: "CITY RIGHT" },
      { start: 5.16, end: 5.46, text: "NOW WITH" },
      { start: 5.46, end: 5.88, text: "KNIVES HIDDEN" },
      { start: 5.88, end: 6.24, text: "UNDER THEIR" },
      { start: 6.24, end: 6.54, text: "TOGAS." },
      { start: 7.16, end: 7.54, text: "BY NOON," },
      { start: 7.98, end: 8.26, text: "CAESAR IS" },
      { start: 8.26, end: 8.44, text: "DEAD." },
      { start: 9.18, end: 9.48, text: "AND ME?" },
      { start: 10, end: 10.46, text: "I'M RIGHT" },
      { start: 10.46, end: 10.64, text: "IN THE" },
      { start: 10.64, end: 10.92, text: "MIDDLE OF" },
      { start: 10.92, end: 11.02, text: "IT." },
    ],
  },
  {
    id: "clip2",
    duration: 8.057007,
    captions: [
      { start: 0, end: 0.7, text: "ONE RECTANGLE." },
      { start: 1.16, end: 1.8, text: "SIX METERS." },
      { start: 2.28, end: 2.54, text: "ZERO PINS" },
      { start: 2.54, end: 2.84, text: "WHERE I" },
      { start: 2.84, end: 3.36, text: "NEED PINS." },
      { start: 4.06, end: 4.4, text: "THEY INVENTED" },
      { start: 4.4, end: 5.2, text: "CONCRETE BEFORE" },
      { start: 5.2, end: 5.58, text: "THE SAFETY" },
      { start: 5.58, end: 5.94, text: "PIN." },
      { start: 6.38, end: 6.54, text: "STAY." },
      { start: 7.22, end: 7.7, text: "STAY." },
    ],
  },
  {
    id: "clip3",
    duration: 10.053991,
    captions: [
      { start: 0.46, end: 1.16, text: "OKAY, WHEN" },
      { start: 1.16, end: 1.56, text: "IN ROME —" },
      { start: 2.14, end: 3.66, text: "IT'S VINEGAR." },
      { start: 4.08, end: 4.24, text: "WHY IS" },
      { start: 4.24, end: 4.52, text: "IT VINEGAR?" },
      { start: 5.28, end: 5.58, text: "WHAT LIVES" },
      { start: 5.58, end: 5.84, text: "IN THE" },
      { start: 5.84, end: 6.04, text: "WATER?" },
      { start: 6.36, end: 6.72, text: "BEST NOT" },
      { start: 6.72, end: 7.22, text: "TO KNOW," },
      { start: 7.22, end: 7.42, text: "DOMINA." },
      { start: 7.894, end: 8.82, text: "3/10." },
      { start: 8.82, end: 9.24, text: "BUILDS CHARACTER," },
      { start: 9.4, end: 9.86, text: "DISSOLVES TEETH." },
    ],
  },
  {
    id: "clip4",
    duration: 5.75,
    captions: [
      { start: 0, end: 0.18, text: "IS HE" },
      { start: 0.18, end: 0.56, text: "COMING OR" },
      { start: 0.56, end: 0.78, text: "NOT?" },
      { start: 1.08, end: 1.28, text: "HE IS" },
      { start: 1.28, end: 1.58, text: "NOT." },
      { start: 1.96, end: 2.6, text: "CALPURNIA DREAMT" },
      { start: 2.6, end: 2.96, text: "HIM DEAD." },
      { start: 3.18, end: 3.5, text: "DECIUS HAS" },
      { start: 3.5, end: 3.82, text: "GONE TO" },
      { start: 3.82, end: 4.32, text: "FETCH HIM." },
      { start: 4.32, end: 4.56, text: "ONE DOES" },
      { start: 4.56, end: 5.18, text: "NOT DECLINE" },
      { start: 5.18, end: 5.64, text: "DECIUS." },
    ],
  },
  {
    id: "clip5",
    duration: 8.057007,
    captions: [
      { start: 1.34, end: 1.94, text: "YOU TOLD" },
      { start: 1.94, end: 2.2, text: "HIM." },
      { start: 2.72, end: 2.96, text: "BEWARE THE" },
      { start: 2.96, end: 3.46, text: "IDES." },
      { start: 4.24, end: 4.66, text: "THE IDES" },
      { start: 4.66, end: 4.92, text: "ARE NOT" },
      { start: 4.92, end: 5.5, text: "YET ENDED." },
      { start: 6.42, end: 6.64, text: "...RIGHT." },
      { start: 6.86, end: 7.02, text: "I'M GOING" },
      { start: 7.02, end: 7.18, text: "TO GO" },
      { start: 7.18, end: 7.5, text: "STAND IN" },
      { start: 7.5, end: 7.74, text: "THE ROAD." },
    ],
  },
  {
    id: "clip6",
    duration: 12.050998,
    captions: [
      { start: 0.96, end: 1.76, text: "MAKE WAY —" },
      { start: 2.08, end: 2.56, text: "PETITIONS FOR" },
      { start: 2.56, end: 2.86, text: "CAESAR!" },
      { start: 4.14, end: 4.46, text: "IN MY" },
      { start: 4.46, end: 5.14, text: "TIME, WHEN" },
      { start: 5.14, end: 5.38, text: "A LETTER" },
      { start: 5.38, end: 5.98, text: "CAN'T WAIT," },
      { start: 6.2, end: 6.72, text: "WE MARK" },
      { start: 6.72, end: 6.94, text: "IT." },
      { start: 7.4, end: 7.42, text: "RED." },
      { start: 7.66, end: 8.888, text: "MEANS READ-THIS-FIRST." },
      { start: 9.22, end: 9.6, text: "RED." },
      { start: 10.28, end: 10.74, text: "READ FIRST." },
      { start: 11.36, end: 11.64, text: "A FINE" },
      { start: 11.64, end: 11.9, text: "SYSTEM." },
    ],
  },
  {
    id: "clip7",
    duration: 13.072834,
    captions: [
      { start: 0, end: 0.714, text: "READ IT" },
      { start: 0.714, end: 1.786, text: "YOURSELF —" },
      { start: 1.786, end: 2.5, text: "ALONE!" },
      { start: 2.5, end: 3.465, text: "THE RED" },
      { start: 3.465, end: 4.108, text: "ONE!" },
      { start: 4.108, end: 5.394, text: "RED MEANS" },
      { start: 5.394, end: 5.6, text: "FIRST—" },
      { start: 10.2, end: 10.88, text: "THE SHERIFF" },
      { start: 10.88, end: 11.92, text: "IN 1875" },
      { start: 11.92, end: 12.22, text: "AT LEAST" },
      { start: 12.22, end: 12.6, text: "TIPPED HIS" },
      { start: 12.6, end: 12.84, text: "HAT." },
    ],
  },
  {
    id: "clip7b",
    duration: 9.055782,
    captions: [
      { start: 0, end: 0.32, text: "YOU SHOULD" },
      { start: 0.32, end: 0.7, text: "TAKE YOUR" },
      { start: 0.7, end: 1.34, text: "GUARDS TODAY." },
      { start: 2.36, end: 2.58, text: "I'VE HAD" },
      { start: 2.58, end: 3.14, text: "GUARDS ENOUGH" },
      { start: 3.14, end: 3.56, text: "FOR ONE" },
      { start: 3.56, end: 4.02, text: "LIFETIME." },
      { start: 4.82, end: 5.06, text: "BETTER TO" },
      { start: 5.06, end: 5.56, text: "DIE ONCE" },
      { start: 5.56, end: 6.28, text: "THAN LIVE" },
      { start: 6.28, end: 6.7, text: "AFRAID OF" },
      { start: 6.7, end: 6.9, text: "IT." },
    ],
  },
  {
    id: "clip9",
    duration: 3.125,
    captions: [], // no dialogue — remaining footage is pure sound/faces/action
  },
  {
    id: "clip10",
    duration: 8.057007,
    captions: [
      { start: 0, end: 0.74, text: "HE HELD" },
      { start: 0.74, end: 1.04, text: "IT." },
      { start: 2.42, end: 3.1, text: "HE HELD" },
      { start: 3.1, end: 3.62, text: "THE WARNING" },
      { start: 3.62, end: 4.2, text: "IN HIS" },
      { start: 4.2, end: 4.64, text: "HAND." },
      { start: 5.94, end: 6.56, text: "HE JUST" },
      { start: 6.56, end: 7.28, text: "NEVER OPENED" },
      { start: 7.28, end: 7.82, text: "HIS HAND." },
    ],
  },
  {
    id: "clip11",
    duration: 13.072834,
    captions: [
      { start: 0, end: 0.46, text: "THEY DID" },
      { start: 0.46, end: 0.72, text: "IT TO" },
      { start: 0.72, end: 1.06, text: "SAVE THE" },
      { start: 1.06, end: 1.36, text: "REPUBLIC." },
      { start: 2.94, end: 3.28, text: "IT DIES" },
      { start: 3.28, end: 3.6, text: "IN THERE" },
      { start: 3.6, end: 4, text: "WITH HIM —" },
      { start: 4.4, end: 4.86, text: "WHAT COMES" },
      { start: 4.86, end: 5.36, text: "NEXT IS" },
      { start: 5.36, end: 5.76, text: "EMPERORS," },
      { start: 6.26, end: 6.64, text: "FOR FIVE" },
      { start: 6.64, end: 7.36, text: "HUNDRED YEARS." },
      { start: 8.58, end: 8.82, text: "AND THEY'RE" },
      { start: 8.82, end: 9.34, text: "RENAMING A" },
      { start: 9.34, end: 9.74, text: "MONTH FOR" },
      { start: 9.74, end: 9.94, text: "HIM." },
      { start: 10.94, end: 11.28, text: "YOU'VE SAID" },
      { start: 11.28, end: 11.66, text: "HIS NAME" },
      { start: 11.66, end: 12.22, text: "EVERY JULY" },
      { start: 12.22, end: 12.6, text: "OF YOUR" },
      { start: 12.6, end: 12.84, text: "LIFE." },
    ],
  },
  {
    id: "clip11b",
    duration: 10.041667,
    captions: [
      // Regenerated 2026-08-24 — new closing line + emotional performance,
      // owner-approved. See captions_data_lines_backup.mjs for the full
      // investigation into the sign-off line's exact wording (initially
      // mis-concluded as NOT "Hazel", corrected after a fuller check).
      { start: 0.714, end: 1.62, text: "TWENTY-THREE WOUNDS." },
      { start: 2.26, end: 2.66, text: "ONLY ONE" },
      { start: 2.66, end: 2.94, text: "OF THEM" },
      { start: 2.94, end: 3.76, text: "WAS NECESSARY." },
      { start: 6.4, end: 7.08, text: "HAZEL —" },
      { start: 7.7, end: 7.98, text: "OUT OF" },
      { start: 7.98, end: 8.3, text: "TIME." },
    ],
  },
];

// Every transition is a TRUE hard cut (plain concat, zero blend) EXCEPT
// clip9 -> clip10, a brief fade-to-black added per explicit owner request
// after a real crossfade was tested and confirmed to ghost (see git
// history / production log for the mid-blend evidence). Baked directly
// into qc/clip9_qc.mp4 (tail) and qc/clip10_qc.mp4 (head), not driven by
// this array (build_final_cut.mjs doesn't consume TRANSITIONS — it's
// documentation here, same as before the caption migration).
export const TRANSITIONS = [
  { after: "clip1", type: "cut" },
  { after: "clip2", type: "cut" },
  { after: "clip3", type: "cut" },
  { after: "clip4", type: "cut" },
  { after: "clip5", type: "cut" },
  { after: "clip6", type: "cut" },
  { after: "clip7", type: "cut" },
  { after: "clip7b", type: "cut" },
  { after: "clip9", type: "fade" },
  { after: "clip10", type: "cut" },
  { after: "clip11", type: "cut" },
];

// Owner-locked 2026-08-23: serif chunk style, channel default (copied
// verbatim from pai-pro-tooling/troy/captions_data.mjs — the reference
// implementation), replacing this episode's previous DejaVu Sans line
// style. ALL-CAPS text comes from the cue data itself; spacing is
// letterspacing in ASS units.
export const SUB_STYLE = {
  fontName: "Liberation Serif",
  fontSize: 50,
  outline: 2,
  shadow: 1,
  marginV: 320,
  marginLR: 60,
  spacing: 2.5,
};
