// Episode 7 (Troy) — caption cue data for qc_pass.mjs.
//
// FORMAT CHANGE (owner-locked 2026-08-23): word-synced CHUNK captions,
// replacing the previous full-line cues. Pattern reverse-engineered from
// the owner's reference reel (cosminacreates Anne Boleyn) and approved
// from a measured-timing demo on clip 4:
//   - 1-2 word chunks, each REPLACING the previous (no accumulation)
//   - a chunk is on screen only while its words are spoken
//   - silence/pauses >= 0.35s = NO caption on screen
//   - hard cut in/out, no animation, ALL CAPS, serif (see SUB_STYLE)
//   - no speaker tags (reference style; owner approved the untagged demo)
//
// TIMING SOURCE: measured per-word timestamps from faster-whisper
// (small.en, int8, script-biased initial_prompt) run on each clip's own
// rendered audio; script text is ground truth (whisper text is only used
// to carry timing — words are fuzzy-matched back to the script so a
// mis-recognition can never change what's displayed). Generated by the
// pipeline in pai-pro-tooling/troy/make_word_chunks.py; per-clip
// corrections where whisper failed against verified frame evidence:
//   - clip3: "4/10." re-clamped to its line window (whisper heard
//     "4 for 10", interpolation had stretched over known silence)
//   - clip5: soldier's shout inaudible to whisper under battle noise —
//     chunks placed from the frame-verified line windows (soldier
//     1.0-2.2, her line 3.5-5.9, mouth-closed gap between)
//   - clip8: bracketed stage direction kept as ONE chunk (not split)
//   - clip10: whisper hallucinated a lead-in and bled the line end to
//     13s — replaced with the frame-verified 9.6-10.3 window
//
// The previous line-level cue data (with full derivation notes) is
// preserved at captions_data_lines_backup.mjs — it remains the
// line-window ground truth the chunk pipeline validates against.

export const CLIPS = [
  {
    id: "clip1",
    duration: 9.055782,
    captions: [
      { start: 0.000, end: 0.380, text: "THE TROJAN" },
      { start: 0.380, end: 0.740, text: "WAR." },
      { start: 1.060, end: 1.520, text: "HOMER SAYS:" },
      { start: 1.520, end: 2.420, text: "TEN YEARS," },
      { start: 2.420, end: 2.700, text: "A THOUSAND" },
      { start: 2.700, end: 3.340, text: "SHIPS, ONE" },
      { start: 3.340, end: 3.780, text: "BIG WOODEN" },
      { start: 3.780, end: 4.060, text: "HORSE." },
      { start: 4.640, end: 4.840, text: "I'M HERE" },
      { start: 4.840, end: 5.340, text: "TO FACT-CHECK" },
      { start: 5.340, end: 5.660, text: "THE MOST" },
      { start: 5.660, end: 6.260, text: "FAMOUS STORY" },
      { start: 6.260, end: 6.860, text: "EVER TOLD." },
      { start: 7.440, end: 7.760, text: "RULE ONE —" },
      { start: 8.260, end: 8.540, text: "STAY OFF" },
      { start: 8.540, end: 8.900, text: "THE PLAIN." },
    ],
  },
  {
    id: "clip2",
    duration: 8.057007,
    captions: [
      { start: 0.000, end: 0.560, text: "ONE RECTANGLE" },
      { start: 0.560, end: 1.160, text: "OF WOOL." },
      { start: 1.780, end: 2.180, text: "FOUR WAYS" },
      { start: 2.180, end: 2.540, text: "TO WEAR" },
      { start: 2.540, end: 2.860, text: "IT." },
      { start: 3.500, end: 3.820, text: "ALL OF" },
      { start: 3.820, end: 4.300, text: "THEM ITCHY." },
      { start: 5.160, end: 5.720, text: "SECOND ERA" },
      { start: 5.720, end: 5.960, text: "IN A" },
      { start: 5.960, end: 6.340, text: "ROW I" },
      { start: 6.340, end: 6.560, text: "HAVE BEEN" },
      { start: 6.560, end: 7.080, text: "DEFEATED BY" },
      { start: 7.080, end: 7.560, text: "A RECTANGLE." },
    ],
  },
  {
    id: "clip3",
    duration: 9.055782,
    captions: [
      { start: 0.520, end: 1.000, text: "THE WINE" },
      { start: 1.000, end: 1.240, text: "HAS BEEN" },
      { start: 1.240, end: 1.760, text: "WATERED FIVE" },
      { start: 1.760, end: 2.120, text: "TIMES." },
      { start: 2.580, end: 2.940, text: "SO IT'S" },
      { start: 2.940, end: 3.180, text: "A RUMOR" },
      { start: 3.180, end: 3.580, text: "OF WINE." },
      { start: 3.880, end: 4.040, text: "IT IS" },
      { start: 4.040, end: 4.420, text: "A MEMORY" },
      { start: 4.420, end: 4.800, text: "OF WINE." },
      { start: 6.330, end: 7.360, text: "4/10." },
      { start: 7.380, end: 7.680, text: "THE CAKE" },
      { start: 7.680, end: 7.980, text: "COULD STOP" },
      { start: 7.980, end: 8.280, text: "AN ARROW." },
      { start: 8.560, end: 8.760, text: "I'M KEEPING" },
      { start: 8.760, end: 8.980, text: "IT." },
    ],
  },
  {
    id: "clip4",
    duration: 13.072834,
    captions: [
      { start: 3.560, end: 4.280, text: "YOU TIE" },
      { start: 4.280, end: 4.740, text: "KNOTS LIKE" },
      { start: 4.740, end: 5.240, text: "A SAILOR." },
      { start: 5.620, end: 6.020, text: "THANK YOU." },
      { start: 6.360, end: 6.880, text: "SAILORS DROWN." },
      { start: 7.160, end: 7.620, text: "KRETHON'S KNOT." },
      { start: 8.060, end: 8.360, text: "TIES TIGHTER" },
      { start: 8.360, end: 8.760, text: "THAN ANYONE" },
      { start: 8.760, end: 9.140, text: "I'VE MET." },
      { start: 9.560, end: 9.920, text: "WATER TO" },
      { start: 9.920, end: 10.360, text: "THE SHIELD" },
      { start: 10.360, end: 10.800, text: "LINE AT" },
      { start: 10.800, end: 11.120, text: "DAWN." },
      { start: 11.720, end: 12.140, text: "STAY LOW." },
    ],
  },
  {
    id: "clip5",
    duration: 6.060000,
    captions: [
      { start: 1.000, end: 1.700, text: "WATER GIRL!" },
      { start: 1.750, end: 2.200, text: "DOWN!" },
      { start: 3.500, end: 3.950, text: "OKAY." },
      { start: 5.080, end: 5.780, text: "THAT'S NEW." },
    ],
  },
  {
    id: "clip6",
    duration: 12.050998,
    captions: [
      { start: 0.000, end: 0.580, text: "THE FOOD" },
      { start: 0.580, end: 1.040, text: "WAS BETTER" },
      { start: 1.040, end: 1.460, text: "THE FIRST" },
      { start: 1.460, end: 2.020, text: "THREE YEARS." },
      { start: 3.300, end: 3.700, text: "HE WALKS" },
      { start: 3.700, end: 4.080, text: "NOW." },
      { start: 4.780, end: 5.200, text: "MY SON." },
      { start: 7.220, end: 7.780, text: "SOMEWHERE..." },
      { start: 7.780, end: 8.180, text: "HE WALKS." },
    ],
  },
  {
    id: "clip7",
    duration: 14.070998,
    captions: [
      { start: 0.000, end: 0.400, text: "ACHILLES." },
      { start: 1.240, end: 1.860, text: "NINE YEARS." },
      { start: 2.140, end: 2.420, text: "THEY SAY" },
      { start: 2.420, end: 2.720, text: "YOU COULD" },
      { start: 2.720, end: 3.080, text: "END THIS" },
      { start: 3.080, end: 3.620, text: "WAR TOMORROW," },
      { start: 3.840, end: 4.040, text: "IF YOU" },
      { start: 4.040, end: 4.240, text: "FOUGHT." },
      { start: 4.400, end: 4.700, text: "WHY DON'T" },
      { start: 4.700, end: 5.040, text: "YOU?" },
      { start: 5.040, end: 5.520, text: "AGAMEMNON TOOK" },
      { start: 5.520, end: 5.860, text: "WHAT WAS" },
      { start: 5.860, end: 6.140, text: "MINE." },
      { start: 6.460, end: 6.760, text: "I WON'T" },
      { start: 6.760, end: 7.020, text: "HAND HIM" },
      { start: 7.020, end: 7.400, text: "MY SWORD" },
      { start: 7.400, end: 7.720, text: "TOO." },
      { start: 8.620, end: 9.100, text: "THAT'S NOT" },
      { start: 9.100, end: 9.520, text: "STRATEGY." },
      { start: 10.200, end: 10.580, text: "THAT'S A" },
      { start: 10.580, end: 10.940, text: "GRUDGE WITH" },
      { start: 10.940, end: 11.260, text: "AN ARMY" },
      { start: 11.260, end: 11.840, text: "BEHIND IT." },
      { start: 11.840, end: 12.040, text: "I HAVE" },
      { start: 12.040, end: 12.440, text: "NEVER BEEN" },
      { start: 12.440, end: 12.860, text: "MORE SCARED" },
      { start: 12.860, end: 13.320, text: "OF ANYONE" },
      { start: 13.320, end: 13.660, text: "IN MY" },
      { start: 13.660, end: 13.840, text: "LIFE." },
    ],
  },
  {
    id: "clip8",
    duration: 12.050998,
    captions: [
      { start: 0.000, end: 0.520, text: "BURIAL TRUCE." },
      { start: 1.020, end: 1.700, text: "ONE AFTERNOON —" },
      { start: 2.100, end: 2.480, text: "BOTH SIDES" },
      { start: 2.480, end: 2.940, text: "COLLECT THEIR" },
      { start: 2.940, end: 3.160, text: "DEAD." },
      { start: 3.580, end: 3.820, text: "AND I'M" },
      { start: 3.820, end: 4.260, text: "WALKING WATER" },
      { start: 4.260, end: 4.460, text: "TO THE" },
      { start: 4.460, end: 4.920, text: "WALLS, BECAUSE" },
      { start: 4.920, end: 5.500, text: "APPARENTLY THAT'S" },
      { start: 5.500, end: 5.720, text: "WHO I" },
      { start: 5.720, end: 6.140, text: "AM NOW." },
      { start: 7.240, end: 7.720, text: "SAME WATER." },
      { start: 8.360, end: 8.820, text: "BOTH SIDES." },
      { start: 8.850, end: 10.400, text: "[CALLS DOWN, IN HIS OWN TONGUE]" },
      { start: 10.420, end: 10.720, text: "HE'S ABOUT" },
      { start: 10.720, end: 10.980, text: "THE AGE" },
      { start: 10.980, end: 11.540, text: "KRETHON'S SON" },
      { start: 11.540, end: 11.860, text: "WOULD BE." },
    ],
  },
  {
    id: "clip9",
    duration: 8.057007,
    captions: [
      { start: 0.000, end: 0.280, text: "OKAY." },
      { start: 0.700, end: 0.980, text: "THE HORSE" },
      { start: 0.980, end: 1.300, text: "PLAN..." },
      { start: 1.980, end: 2.180, text: "GIANT WOODEN" },
      { start: 2.180, end: 2.780, text: "HORSE — SOLDIERS" },
      { start: 2.780, end: 3.400, text: "HIDING INSIDE." },
      { start: 3.640, end: 3.720, text: "YES?" },
      { start: 4.140, end: 4.300, text: "A WHAT?" },
      { start: 4.300, end: 4.560, text: "WHO WOULD" },
      { start: 4.560, end: 5.000, text: "DRAG IT?" },
      { start: 5.000, end: 5.220, text: "...HOW MANY" },
      { start: 5.220, end: 5.440, text: "SOLDIERS?" },
      { start: 5.600, end: 5.980, text: "NO HORSE." },
      { start: 6.380, end: 6.640, text: "YET." },
      { start: 6.940, end: 7.320, text: "REMEMBER I" },
      { start: 7.320, end: 7.540, text: "SAID IT" },
      { start: 7.540, end: 7.840, text: "HERE FIRST." },
    ],
  },
  {
    id: "clip10",
    duration: 15.069002,
    captions: [
      { start: 9.600, end: 10.000, text: "—STAY WITH" },
      { start: 10.000, end: 10.300, text: "ME—" },
    ],
  },
  {
    id: "clip11",
    duration: 9.055782,
    captions: [
      { start: 0.000, end: 0.580, text: "NINE YEARS" },
      { start: 0.580, end: 1.160, text: "OF THIS." },
      { start: 2.320, end: 2.940, text: "EVERY NIGHT." },
      { start: 3.740, end: 4.340, text: "ON BOTH" },
      { start: 4.340, end: 4.780, text: "SIDES OF" },
      { start: 4.780, end: 5.200, text: "THAT WALL." },
      { start: 6.720, end: 7.180, text: "AND HOMER" },
      { start: 7.180, end: 7.520, text: "IS GOING" },
      { start: 7.520, end: 7.780, text: "TO MAKE" },
      { start: 7.780, end: 8.160, text: "IT SOUND" },
      { start: 8.160, end: 8.820, text: "GLORIOUS." },
    ],
  },
  {
    id: "clip12",
    duration: 13.072834,
    captions: [
      { start: 0.000, end: 0.400, text: "GET HOME," },
      { start: 0.600, end: 0.820, text: "KRETHON." },
      { start: 1.120, end: 1.300, text: "COUNT THEM" },
      { start: 1.300, end: 1.620, text: "OUT LOUD" },
      { start: 1.620, end: 1.980, text: "TO HIM." },
      { start: 2.800, end: 3.020, text: "IN THREE" },
      { start: 3.020, end: 3.540, text: "THOUSAND YEARS," },
      { start: 3.540, end: 3.800, text: "A MAN" },
      { start: 3.800, end: 4.300, text: "FINDS THIS" },
      { start: 4.300, end: 4.660, text: "CITY WITH" },
      { start: 4.660, end: 4.960, text: "A SHOVEL" },
      { start: 4.960, end: 5.300, text: "IN ONE" },
      { start: 5.300, end: 5.640, text: "HAND AND" },
      { start: 5.640, end: 5.940, text: "HOMER IN" },
      { start: 5.940, end: 6.220, text: "THE OTHER." },
      { start: 6.700, end: 7.060, text: "THE POEM" },
      { start: 7.060, end: 7.380, text: "IS THE" },
      { start: 7.380, end: 7.620, text: "MAP." },
      { start: 8.700, end: 9.080, text: "WHETHER IT" },
      { start: 9.080, end: 9.560, text: "HAPPENED LIKE" },
      { start: 9.560, end: 9.900, text: "THE SONG" },
      { start: 9.900, end: 10.420, text: "SAYS — IT" },
      { start: 10.420, end: 10.820, text: "HAPPENED FOR" },
      { start: 10.820, end: 11.000, text: "THEM." },
      { start: 11.920, end: 12.080, text: "HAZEL —" },
      { start: 12.580, end: 12.780, text: "OUT OF" },
      { start: 12.780, end: 12.920, text: "TIME." },
    ],
  },
];

// Cross-episode pipeline rule (creative-direction.md §16, owner-locked
// 2026-08-20): every transition is a TRUE HARD CUT — no dissolves, no
// blend window. No title card either (OPENING LAW retires the card).
export const TRANSITIONS = [
  { after: "clip1", type: "cut" },
  { after: "clip2", type: "cut" },
  { after: "clip3", type: "cut" },
  { after: "clip4", type: "cut" },
  { after: "clip5", type: "cut" },
  { after: "clip6", type: "cut" },
  { after: "clip7", type: "cut" },
  { after: "clip8", type: "cut" },
  { after: "clip9", type: "cut" },
  { after: "clip10", type: "cut" },
  { after: "clip11", type: "cut" },
];

// Owner-locked 2026-08-23: serif chunk style copied from the reference
// reel (closest local font to its Times-like serif). ALL-CAPS text comes
// from the cue data itself; spacing is letterspacing in ASS units.
export const SUB_STYLE = {
  fontName: "Liberation Serif",
  fontSize: 50,
  outline: 2,
  shadow: 1,
  marginV: 320,
  marginLR: 60,
  spacing: 2.5,
};
